# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81bbe66e4a5d4447204f536d02f7f3905d7ee5786c193b9b6661feed3df5436d5852f53dc317a433f0edda4269282290b44bb83cdb7bc4a67d195110e7b53f74

test:
  secret_key_base: 913bc5f340a38191ab18f2ef53472e7ecfad7f1e9c1cc82cc7f96a87164a8008ab717de6e32a919b2bc3dde355cc514a0ee2ed3d4ea44eeb2c39d7b66ad4e09c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
